
# pattern_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON LBRACE NUMBER RBRACE WORDpattern : words\n               | sub\n               | words subpattern : words sub pattern\n               | sub patternsub : LBRACE WORD RBRACE\n           | LBRACE NUMBER RBRACE\n           | LBRACE WORD COLON WORD RBRACE\n           | LBRACE WORD COLON NUMBER RBRACEsub : LBRACE WORD NUMBER COLON WORD RBRACEsub : LBRACE WORD NUMBER RBRACEwords : WORD\n             | NUMBER\n             | NUMBER words\n             | WORD words'
    
_lr_action_items = {'WORD':([0,3,4,5,6,7,14,15,17,20,21,22,23,25,],[4,4,4,4,11,4,-6,18,-7,24,-11,-8,-9,-10,]),'NUMBER':([0,3,4,5,6,7,11,14,15,17,21,22,23,25,],[5,5,5,5,12,5,16,-6,19,-7,-11,-8,-9,-10,]),'LBRACE':([0,2,3,4,5,7,9,10,14,17,21,22,23,25,],[6,6,6,-12,-13,6,-15,-14,-6,-7,-11,-8,-9,-10,]),'$end':([1,2,3,4,5,7,8,9,10,13,14,17,21,22,23,25,],[0,-1,-2,-12,-13,-3,-5,-15,-14,-4,-6,-7,-11,-8,-9,-10,]),'RBRACE':([11,12,16,18,19,24,],[14,17,21,22,23,25,]),'COLON':([11,16,],[15,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'pattern':([0,3,7,],[1,8,13,]),'words':([0,3,4,5,7,],[2,2,9,10,2,]),'sub':([0,2,3,7,],[3,7,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pattern","S'",1,None,None,None),
  ('pattern -> words','pattern',1,'p_pattern','pattern_grammar.py',32),
  ('pattern -> sub','pattern',1,'p_pattern','pattern_grammar.py',33),
  ('pattern -> words sub','pattern',2,'p_pattern','pattern_grammar.py',34),
  ('pattern -> words sub pattern','pattern',3,'p_pattern_multiple','pattern_grammar.py',39),
  ('pattern -> sub pattern','pattern',2,'p_pattern_multiple','pattern_grammar.py',40),
  ('sub -> LBRACE WORD RBRACE','sub',3,'p_sub','pattern_grammar.py',46),
  ('sub -> LBRACE NUMBER RBRACE','sub',3,'p_sub','pattern_grammar.py',47),
  ('sub -> LBRACE WORD COLON WORD RBRACE','sub',5,'p_sub','pattern_grammar.py',48),
  ('sub -> LBRACE WORD COLON NUMBER RBRACE','sub',5,'p_sub','pattern_grammar.py',49),
  ('sub -> LBRACE WORD NUMBER COLON WORD RBRACE','sub',6,'p_sub_numbered','pattern_grammar.py',65),
  ('sub -> LBRACE WORD NUMBER RBRACE','sub',4,'p_sub_numbered_untyped','pattern_grammar.py',71),
  ('words -> WORD','words',1,'p_words','pattern_grammar.py',78),
  ('words -> NUMBER','words',1,'p_words','pattern_grammar.py',79),
  ('words -> NUMBER words','words',2,'p_words','pattern_grammar.py',80),
  ('words -> WORD words','words',2,'p_words','pattern_grammar.py',81),
]
